// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMkhOgzL8SqHyDYGpJGIGeukpzF7otehY',
    appId: '1:945589001206:web:ff8139e9c74e1827b0c5d7',
    messagingSenderId: '945589001206',
    projectId: 'billwise2-e6e3c',
    authDomain: 'billwise2-e6e3c.firebaseapp.com',
    databaseURL: 'https://billwise2-e6e3c-default-rtdb.firebaseio.com',
    storageBucket: 'billwise2-e6e3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd0hw1sJlJdxaJ9VDwCtBWyIL-05aBpaQ',
    appId: '1:945589001206:android:da94327672552f16b0c5d7',
    messagingSenderId: '945589001206',
    projectId: 'billwise2-e6e3c',
    databaseURL: 'https://billwise2-e6e3c-default-rtdb.firebaseio.com',
    storageBucket: 'billwise2-e6e3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9wAU_yuuH9UZOfCtFpUpMnRZ5Vz9R6x0',
    appId: '1:945589001206:ios:490b15fd8d533fd2b0c5d7',
    messagingSenderId: '945589001206',
    projectId: 'billwise2-e6e3c',
    databaseURL: 'https://billwise2-e6e3c-default-rtdb.firebaseio.com',
    storageBucket: 'billwise2-e6e3c.firebasestorage.app',
    iosBundleId: 'com.example.billwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9wAU_yuuH9UZOfCtFpUpMnRZ5Vz9R6x0',
    appId: '1:945589001206:ios:490b15fd8d533fd2b0c5d7',
    messagingSenderId: '945589001206',
    projectId: 'billwise2-e6e3c',
    databaseURL: 'https://billwise2-e6e3c-default-rtdb.firebaseio.com',
    storageBucket: 'billwise2-e6e3c.firebasestorage.app',
    iosBundleId: 'com.example.billwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMkhOgzL8SqHyDYGpJGIGeukpzF7otehY',
    appId: '1:945589001206:web:0fba93293d7498e3b0c5d7',
    messagingSenderId: '945589001206',
    projectId: 'billwise2-e6e3c',
    authDomain: 'billwise2-e6e3c.firebaseapp.com',
    databaseURL: 'https://billwise2-e6e3c-default-rtdb.firebaseio.com',
    storageBucket: 'billwise2-e6e3c.firebasestorage.app',
  );
}
